---
#
# Ansible managed
#
repository:
  description: Install and configure Elasticsearch on your system.
  homepage: https://robertdebock.nl/
  topics: elasticsearch, ansible, molecule, tox, playbook, hacktoberfest
