---
# tasks file for elasticsearch

- name: include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install elasticsearch
  ansible.builtin.package:
    name: "{{ elasticsearch_packages }}"
    state: present

- name: start elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
